### ISSUE TITLE
Remove repo?

### ISSUE THREAD

**Issue by mig42** [dickp/plasticscm-hudson-plugin#3]
Hi!

It would be great to remove this repo so the one under the Jenkins organization (https://github.com/jenkinsci) becomes the source of all forks.

This repo isn't getting any activity, so I figured that it would be a good idea to delete it. That way users won't see any "forked from" in the repo linked in the Jenkins UI.

Thanks!

**Comment by dickp** [comment]
Hi Miguel!

I have no problem with that, especially if it's causing confusion for the real repo.

- Dick

**Comment by mig42** [comment]
Thanks Dick! I think it will be a good idea. The Jenkins plugin guidelines recommend it, too.

Cheers,
Miguel

**Comment by dickp** [comment]
Ok, I'll delete it in the next few days
